rango/urls.py
from django.conf.urls        import include, url
from django.conf             import settings
from django.views.static     import serve
from django.conf.urls.static import static
from rango                   import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^category/(?P<category_name_slug>[\w\-]*)/$', views.category, name='category'),
    url(r'^rango/category/(?P<category_name_slug>[\w\-]*)/$', views.category, name='category'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^like_category/(?P<category_id>[0-9]+)/$', views.like_category, name="like_category"),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^change_password/password_change_complete/$', views.password_change_complete, 
        name='password_change_complete'),
    url(r'^goto/(?P<page_id>[0-9]+)/$', views.track_url, name='goto'),
    url(r'^add_profile/registration_complete/$', views.registration_complete, 
        name='registration_complete'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^profile/edit_profile/profile_edit_complete/$', views.profile_edit_complete, 
        name='profile_edit_complete'),
    url(r'^search/$', views.search, name='search'),
    url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
    
]

# Do not use this for production!
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, { 
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

tango_with_django_project/urls.py
from django.conf.urls                   import include, url
from django.contrib                     import admin
from registration.backends.simple.views import RegistrationView


# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/rango/add_profile'


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls')),
    url(r'^$'     , 'rango.views.index', name='index'),
    #Add in this url pattern to override the default pattern in accounts.
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

rango/models.py
from django.db                      import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models     import User


class Category(models.Model):
    
    name  = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug  = models.SlugField(unique=True)
    

    class Meta:
        verbose_name_plural = "Categories"


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if (self.views < 0):
            self.views = 0
        if (self.likes < 0):
            self.likes = 0

        super(Category, self).save(*args, **kwargs)


    def __str__(self):
        return self.name


    def __repr__(self):
        return "<Category(name={}, views={}, likes={}, slug={})>".format \
            (
                self.name, 
                self.views, 
                self.likes,
                self.slug,
            )


class Page(models.Model):
    
    category = models.ForeignKey(Category)
    title    = models.CharField(max_length=128)
    url      = models.URLField()
    views    = models.IntegerField(default=0)


    def save(self, *args, **kwargs):
        if self.views < 0:
            self.views = 0

        super(Page, self).save(*args, **kwargs)


    def __str__(self):
        return self.title


    def __repr__(self):
        return "<Page(category={}, title={}, url={}, views={})>".format \
            (
                self.category,
                self.title, 
                self.url, 
                self.views,
            )


class UserProfile(models.Model):
    
    # This line is requires. Links UserProfile to User model.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    
    # Override the __str__ method to return something meaningful!
    def __str__(self):
        return repr(self)

    
    def __repr__(self):
        return "<UserProfile(username={}, website={}, picture={})>".format(
                self.user.username, 
                self.website,
                self.picture,
            )

rango/views.py
from datetime                       import datetime
from django.shortcuts               import render, redirect
from django.http                    import HttpResponse, HttpResponseRedirect
from django.template.loader         import get_template
from django.template                import Context, RequestContext
from django.contrib.auth            import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models.query         import QuerySet
from rango.models                   import Category, Page, UserProfile, User
from rango.forms                    import CategoryForm, PageForm
from rango.forms                    import UserForm, UserProfileForm
from rango.forms                    import PasswordChangeForm


def index(request):
    # Query the database for a list of ALL categories currently stored.
    # Order the categories by no. likes in descending order.
    # Retrieve the top 5 only - or all if less than 5.
    # Place the list in our context_dict dictionary which will be passed to the template engine.
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    visits = request.session.get('visits')
    if not visits:
        visits = 1
    reset_last_visit_time = False

    last_visit = request.session.get('last_visit')
    # Does the cookie last_visit exist?
    if last_visit is not None:
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

        # If it has been more than a day since the last visit
        if (datetime.now() - last_visit_time).seconds > 0:
            visits += 1
            # ... and flag that the cookie last visit needs to be updated
            reset_last_visit_time = True
    else:
        # Cookie last_visit doesn't exist, so flag that it should be set.
        reset_last_visit_time = True

    # Append the new cookie information if we visited previously.
    if reset_last_visit_time:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits
    
    context_dict['visits'] = visits
    context = RequestContext(request, context_dict)
    template = get_template('rango/index.html')
    response = HttpResponse(template.render(context))
    
    return response


def about(request):
    context_dict = {'descriptor': 'ABOUT'}
    if request.session.has_key('visits'):
        visits = request.session.get('visits')
    else:
        visits = 1

    last_visit = request.session.get('last_visit')
    # Does the cookie last_visit exist?
    if last_visit:
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

        # If it has been more than a day since the last visit
        if (datetime.now() - last_visit_time).seconds > 0:
            visits += 1
            # ... and flag that the cookie last visit needs to be updated
            reset_last_visit_time = True
    else:
        # Cookie last_visit doesn't exist, so flag that it should be set.
        reset_last_visit_time = True

    # Append the new cookie information if we visited previously.
    if reset_last_visit_time:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits

    context_dict['visits'] = visits
    context = RequestContext(request, context_dict)
    template = get_template('rango/about.html')

    return HttpResponse(template.render(context))


def category(request, category_name_slug):
    # Create a context dictional which we can pass to the template rendering engine.
    context_dict = {}

    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() metho returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name

        # Retrieve all of the associated pages.
        pages = list(Page.objects.filter(category=category).order_by('-views'))

        # Adds our result list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
        context_dict['category_name_slug'] = category.slug
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything - the template displays the "no category" message for us.
        print(category_name_slug)
        context_dict['category_name_slug'] = category_name_slug

    if request.method == 'POST':
        # We don't have to use bing if we don't want to.
        query = request.POST.get('query', '')
        if query != '':
            pages = context_dict.get('pages', [])
            # search_results = list(run_query(query))
            search_results = list(filter(lambda page: query in page.title, pages))
            context_dict['pages'] = search_results  

        context = RequestContext(request, context_dict)
    # Treat request as a 'GET'    
    else:
        context = RequestContext(request, context_dict)

    return render(request, 'rango/category.html', context)


@login_required
def add_category(request):
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)

            # Now call the index() view.
            # The user will be shown the homepage.
            return index(request)
        else:
            # The supplied form contains errors. Just print them to the terminal.
            print(form.errors)
    else:
        # If the request was not a POST, display the form to enter details.
        form = CategoryForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    # We need to use a RequestContext here since Django requires all
    # forms that use the 'POST' method in request have a csrf token. The RequestContext
    # retains the original request containing the csrf token. The Context class does not,
    # so when the form data is submitted to Django, it throws a 403 error since it detects
    # the csrf cookie as being not set.
    context = RequestContext(request, {'form': form})
    return render(request, 'rango/add_category.html', context)


@login_required
def like_category(request, category_id):
    
    try:
        category = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        category = None

    if request.method == 'GET':
        if category:
            #Update the number of likes for category
            category.likes += 1
            category.save()
            likes = category.likes
        else:
            # Category does not exist.
            likes = 0

        return HttpResponse("{} likes".format(likes))    


@login_required
def add_page(request, category_name_slug):

    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()
                # probably better to use a redirect here.
                return category(request, category_name_slug)
        else:
            print(form.errors)
    else:
        form = PageForm()

    context = RequestContext(request, {'form': form, 'category': cat})

    return render(request, 'rango/add_page.html', context)


def register(request):
    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print(user_form.errors, profile_form.errors)

templates/rango/about.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}About Page{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>About</h1>
    </div>
    <div>
        <p>This is <strong>Rango's <b>{{ descriptor }}</b> page!</strong></p>
        <p>You have visited the site on <strong>{{ visits }} occasion(s).</strong>
        <p>Here is a picture of Rango!</p>
        <img src="{% static "images/about.jpg" alt="About Page Picture" %}">
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title %}
    Add Category
{% endblock %}

{% block body_block %}
    <h2 class="form-signin-heading">
        Add a new category
    </h2>
    {% if user.is_authenticated %}
        <form role="form" id="category_form" method="post" action="{% url 'add_category' %}">
            
            {% csrf_token %}
            
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br>
                {{ field }}<br>
            {% endfor %}
            
            <br>
            <input class="btn btn-primary" type="submit" name="submit" value="Add Category">
        </form>
    {% else %}
        <p>You must be logged in to add a category.</p>
    {% endif %}
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title %}
    Add Page
{% endblock %}

{% block body_block %}
    {% if category %}
        {% if user.is_authenticated %}
            <form role="form" id="page_form" method="post" action="{% url 'add_page' category.slug %}">
                <h2 class="form-signin-heading">
                    Add a page to <a href="{% url 'category' category.slug %}">{{ category.name }}</a>
                </h2>

                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}<br>
                    {{ field }}<br>
                {% endfor %}

                <br>
                
                <input class="btn btn-primary" type="submit" name="submit" value="Add Page">
            </form>
        {% else %}
            <p>You must be logged in to add a page.</p>
        {% endif %}
    {% else %}
        <p>This category does not exist.</p>
    {% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
<html lang="en">
  <head>

    {% load rango_extras %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/rango/">Rango</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'index' %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                    <li><a href="{% url 'add_category' %}">Add a New Category</a></li>
                    <li><a href="{% url 'profile' %}">Profile</a></li>
                {% else %}
                    <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                    <li><a href="{% url 'auth_login' %}">Login</a></li>
                {% endif %}
                    <li><a href="{% url 'about' %}">About</a></li>
                    {# <li><a href="{% url 'search' %}">Search</a></li> #}
            </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            {% block side_block %}
                <ul class="nav nav-list">
                    <li class="nav-header">Find a Category</li>
                    <form>
                        <label></label>
                        <li><input  class="search-query span10" type="text" name="suggestion" 
                            value="" id="suggestion" /></li>
                    </form>
                </ul>

                <div id="cats">
                </div>
                {% get_category_list category %}
            {% endblock %}

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <div>
                {% block body_block %}{% endblock %}
            </div>
        </div>
      </div>
    </div>

    {% load staticfiles %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    <!-- jQuery -->
    <script src="{% static "javascripts/jquery-2.1.4.min.js" %}"></script>
    <script src="{% static "javascripts/rango-ajax.js" %}"></script>
    <script src="{% static "javascripts/rango-jquery.js" %}"></script>
  </body>

</html>

templates/rango/category.html
{% extends 'rango/base.html' %}

{% load static %}

{% block title %}
    {% if category_name %}
        {{ category_name }}
    {% else %}
        Category Does Not Exist
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <div class="page-header">
            <h1>{{ category_name }}</h1>
            <span class="badge" id="like-count">{{ category.likes }} likes</span>
        </div>

    
        {# Display the search bar. #}
        <div id="search">
        <div class="row">

            <div class="panel">
                <br>

                <form class="form-inline" id="user_form" method="post" 
                    action="{% url 'category' category.slug %}">
                
                    {% csrf_token %}
                    <label for="id_query">Search Category</label>
                    <br>
                    <!-- Display the search form elements here -->
                    <input class="form-control" type="text" size="50" name="query" value="" id="id_query">
                    <input class="btn btn-primary" type="submit" name="submit" value="Search">
                    <br>
                </form>

                <div class="panel">
                    {% if result_list %}
                    <div class="panel-heading">
                        <h3 class="panel-title">Results</h3>
                        <!-- Display search results in an ordered list -->
                        <div class="panel-body">
                            <div class="list-group">
                                {% for result in result_list %}
                                    <div class="list-group-item">
                                        <h4 class="list-group-item-heading"><a href="{{ result.link }}">{{ result.title }}</a></h4>
                                        <p class="list-group-item-text">{{ result.summary }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        </div>


        {% if pages %}
            <ul class="list-group">
                {% for page in pages %}
                    <li class="list-group-item">
                        <a href="{% url 'goto' page.id %}">{{ page.title }}</a>
                        <span class="badge">
                            {% if page.views > 1 %}
                                {{ page.views }} views
                            {% elif page.views == 1 %}
                                {{ page.views }} view
                            {% endif %}
                        </span>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p><strong>No pages currently in category.</strong></p>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'add_page' category.slug %}" class="btn btn-primary" type="submit" 
                name="submit">
                    Add a new page
            </a>
        {% else %}
            <a href="{% url 'auth_login' %}" class="btn btn-primary" type="submit" 
                name="submit">
                    Log in to add a new page
            </a>
        {% endif %}
            <button class="btn btn-default" id="like-button" data-cat-id="{{ category.id }}"
                data-cat-url="{% url 'like_category' category.id %}">
                
                <span class="glyphicon glyphicon-thumbs-up"</span>
                Like
            </button>
    {% else %}
        <div class="page-header">
            <h1>Category Does Not Exist</h1>
        </div>
        
        <p>The specified category <strong>{{ category_name_slug }}</strong> does not exist!</p>
    {% endif %}

{% endblock %}

templates/rango/cats.html
{% if cats %}
    <ul class="nav nav-sidebar">
        {% for cat in cats %}
            {% if cat == active_cat %}
                <li class="active">
            {% else %}
                <li>
            {% endif %}
                    <a href="{% url 'category'  cat.slug %}">{{ cat.name }}</a>
                </li>
        {% endfor %}
    </ul>
{% else %}
    <ul class="nav nav-sidebar"    
        <li> <strong>There are no categories present.</strong></li>
    </ul>
{% endif %}

templates/rango/edit_profile.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}
    Edit Profile
{% endblock %}

{% block body_block %}
    {% if user.is_authenticated %}
        <div class="page-header">
            <h1>{{ username|capfirst }}'s Profile</h1>
        </div>
        <div class="form-group">
            <form role="form" method="post" action="{% url 'edit_profile' %}"
                enctype="multipart/form-data">
                
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_website">Website:</label>
                    <input class="form-control" id="id_website" maxlength="200"
                        name="website" type="url" placeholder="Website" 
                        value="{{ website }}">
                </div>

                <div class="">
                    <label for="id_picture">Picture:</label>
                    <input class="btn btn-default" id="id_picture" name="picture" 
                        type="file" placeholder="Upload Image" 
                        value="{% static '{{ picture }}' %}">

                </div>
                <div class="">
                    <img src="{% static picture_url %}" alt="Profile Picture">
                </div>
                <input class="btn btn-primary" type="submit" value="Submit">
            </form>
        </div>
    {% else %}
        <p>You must be logged in to edit your profile.</p>
    {% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}

{% block title %}Front Page{% endblock %}

{% block body_block %}
<div class="jumbotron">
    <div class="page-header">
        {% if user.is_authenticated %}
            <h1>Rango says... Hello {{ user.username }}</h1>
        {% else %}
            <h1>Rango Says... Hello World!</h1>
        {% endif %}
    </div>
    
    <div class="row placeholders">
        <div class="col-xs-12 col-sm-6 placeholder">
            {% if categories %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Top {{ pages|length }} Categories</h3>
                    </div>
                </div>
                
                <div>
                    <ul class="list-group">
                        {# Here we add the top number of categories. #}
                        {% for category in categories %}
                            <li class="list-group-item">
                                <a href="{% url 'category' category.slug %}">{{ category.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
        </div>
        <div class="col-xs-12 col-sm-6 placeholder">
            {% if pages %}
                <div class="panel panel-primary">
                    <div class="panel-heading">  
                        <h3 class="panel-title">Top {{ pages|length }} Pages</h3>
                    </div>
                </div>
                
                <div>
                    <ul class="list-group">
                        {# Here we add the top number of pages. #}
                        {% for page in pages %}
                            <li class="list-group-item">
                                <a href="{{ page.url }}">{{ page.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% else %}
                <strong>There are no pages present.</strong>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    {% if login_error %}
        <p>{{ login_error }}</p>
        <form id="login_form" method="post" action="{% url 'login' %}">
            {% csrf_token %}
            Username: 
            <br /><input type="text" name="username" value="{{ old_username }}" size="50" /><br />
            Password: 
            <br /><input type="password" name="password" value="" size="50" /><br />

            <input type="submit" value="Submit" />
        </form>
    {% else %}
        <form id="login_form" method="post" action="{% url 'login' %}">
            {% csrf_token %}
            Username: 
            <br /><input type="text" name="username" value="" size="50" /><br />
            Password: 
            <br /><input type="password" name="password" value="" size="50" /><br />

            <input type="submit" value="Submit" />
        </form>
    {% endif %}
{% endblock %}

templates/rango/password_change_complete.html
{% extends "rango/base.html" %}

{% load i18n %}

{% block body_block %}
    <p>{% trans "Password changed successfully!" %}</p>
{% endblock %}

templates/rango/password_change_form.html
{% extends 'rango/base.html' %}

{% block body_block %}
    <form id="password_change_form" method="post" action="{% url 'change_password' %}">
        {% csrf_token %} 
        
        {% for field in password_change_form.visible_fields %}
            {% if field.errors %}
                {{ field.label }}: {{ field.errors }}
            {% endif %}
        {% endfor %}

        {% for field in password_change_form.visible_fields %}
            <p><strong>{{ field.help_text }}</strong></p>
            <p><strong>{{ field.label}}:</strong></p>
            <p>{{ field }}</p>
        {% endfor %}

        <input type="submit" name='submit' value="Change Password">
    </form>
{% endblock %}